version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: phys-tech
    environment:
      POSTGRES_DB: phys-tech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - my_network
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 2s
      timeout: 2s
      retries: 15

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile  # path to your Dockerfile for the FastAPI app
    container_name: phys-tech-web
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=phys-tech
      - DB_USER=postgres
      - DB_PASS=root
      - AUTH_SECRET=phys-tech-secret
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network

networks:
  my_network: {}

#networks:
#  my_network:
#    driver: bridge
