version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: phys-tech-db
    environment:
      POSTGRES_DB: phys-tech  # Updated to use the "physt-tech" database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    networks:
      - my_network

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile  # path to your Dockerfile for the FastAPI app
    container_name: phys-tech-web
    environment:
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_NAME=phys-tech
      - DB_USER=postgres
      - DB_PASS=root
      - AUTH_SECRET=phys-tech-secret
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
