version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phys-tech-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: phys-tech-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - shared_network

networks:
  shared_network: {}
