"""add_user_contact_and_service_request_comment

Revision ID: 0004
Revises: 0003
Create Date: 2024-02-24 00:48:23.968003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_request', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('user', sa.Column('contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    op.drop_column('service_request', 'comment')
    # ### end Alembic commands ###
