"""service_request_cascade_delete

Revision ID: 0005
Revises: 0004
Create Date: 2024-02-27 15:29:30.360445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_service_request_service', 'service_request', type_='foreignkey')
    op.create_foreign_key('fk_service_request_service', 'service_request', 'service', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_service_request_service', 'service_request', type_='foreignkey')
    op.create_foreign_key('fk_service_request_service', 'service_request', 'service', ['service_id'], ['id'])
    # ### end Alembic commands ###
