"""add_service_request_and_add_relations

Revision ID: 0005
Revises: 0004
Create Date: 2024-01-17 18:37:30.952775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='servicerequeststatus'), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], name='fk_service_request_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='fk_service_request_service'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('service', sa.Column('expected_result', sa.String(), nullable=True))
    op.add_column('service', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('service', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('fk_service_organization', 'service', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('service', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_service_organization', 'service', type_='foreignkey')
    op.alter_column('service', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('service', 'organization_id')
    op.drop_column('service', 'expected_result')
    op.drop_table('service_request')
    op.execute('DROP TYPE servicerequeststatus')
    # ### end Alembic commands ###
