"""update_organization_category_enum

Revision ID: 0006
Revises: 0005
Create Date: 2024-04-10 15:42:59.888285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'organization_category_enum', ['SCIENTIFIC_INSTITUTE', 'UNIVERSITY', 'COMPANY'],
                        [TableReference(table_schema='public', table_name='organization', column_name='category')],
                        enum_values_to_rename=[
                            ('SCIENTIFIC_ORGANIZATION', 'SCIENTIFIC_INSTITUTE'),
                            ('COMMERCIAL_LABORATORY_COMPANY', 'COMPANY')
                        ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'organization_category_enum', ['SCIENTIFIC_ORGANIZATION', 'UNIVERSITY', 'TECHNOPARK', 'COMMERCIAL_LABORATORY_COMPANY'],
                        [TableReference(table_schema='public', table_name='organization', column_name='category')],
                        enum_values_to_rename=[
                            ('SCIENTIFIC_INSTITUTE', 'SCIENTIFIC_ORGANIZATION'),
                            ('COMPANY', 'COMMERCIAL_LABORATORY_COMPANY')
                        ])
    # ### end Alembic commands ###
