"""add_user_events

Revision ID: 0007
Revises: 0006
Create Date: 2024-05-01 21:07:18.279327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_event_user', 'event', 'user', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_event_user', 'event', type_='foreignkey')
    op.drop_column('event', 'created_by_id')
    # ### end Alembic commands ###
