"""add_service_fields

Revision ID: 0008
Revises: 0007
Create Date: 2024-05-11 19:59:13.061846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('technical_specifications', sa.String(), nullable=True))
    op.add_column('service', sa.Column('sample_preparation', sa.String(), nullable=True))
    op.add_column('service', sa.Column('has_certificate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'has_certificate')
    op.drop_column('service', 'sample_preparation')
    op.drop_column('service', 'technical_specifications')
    # ### end Alembic commands ###
