version: '3.8'

services:
  next:
    container_name: science-services-next
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared_network

networks:
  shared_network: {}